pub mod boinc;
pub mod boinc_client;
pub mod boinc_compat;
pub mod config;
pub mod console_display;
pub mod crypto;
pub mod hardware_detection;
pub mod integration_example;
pub mod miner_core;
pub mod miner_tui;
pub mod nuw_worker;
pub mod oracle;
pub mod oracle_profile;
pub mod performance_monitor;
pub mod project_preferences;
pub mod rate_limiter;
pub mod resource_manager;
pub mod security_logger;
pub mod zk_verifier;

// Re-export commonly used types
pub use boinc::{BoincRunner, BoincStats, run_boinc_worker};
pub use config::MinerConfig;
pub use console_display::{ConsoleDisplay, start_console_display};
pub use hardware_detection::{HardwareProfile, HardwareType, detect_hardware_capabilities};
pub use integration_example::{IntegrationManager, IntegrationStatus, run_integration_demo};
pub use miner_core::{MinerCore, MinerStatus, WorkMode, run_miner};
pub use miner_tui::MinerTui;
pub use nuw_worker::{NuwTask, NuwStats, NuwWorker, TaskType, TaskPayload, TaskResult, MinerRegistration};
pub use oracle_profile::{OracleProfileClient, OracleProfileManager, ProjectRecommendation};
pub use performance_monitor::PerformanceMonitor;
pub use project_preferences::{ProjectInfo, ProjectPreferenceManager, ProjectSelection};
pub use rate_limiter::RateLimiter;
pub use resource_manager::{ResourceManager, check_resource_management_support};
pub use security_logger::SecurityLogger;
pub use zk_verifier::{verify_halo2_proof, verify_recursive_snark};
